# This is a basic workflow to help you get started with Actions

name: CI-CD-Hackathon

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  upload-to-aws:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: checkout-changes
        uses: actions/checkout@v4

      - name: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: sync-files
        run: |
          aws s3 sync . arn:aws:s3:::hackathon-bucket-cariel-7-30-2025 --delete

